import { NextRequest, NextResponse } from "next/server";
import { google } from "googleapis";
import crypto from "crypto";
import { decrypt, getProfile, listProfileIds, saveProfile, SyncEvent } from "@/lib/sync-store";

const SOURCE="https://script.google.com/macros/s/AKfycbyALiIAKX30Vrwqb6fOvxXR5i66vnfe4-DCfhnEAY_g59FX_OyaobPYkSwZ2sRwX62fAQ/exec";
const norm=(v:unknown)=>String(v??"").toUpperCase().replace(/[^A-Z0-9]/g,"");
function value(row:any,...names:string[]){for(const name of names){const found=Object.keys(row).find(k=>norm(k)===norm(name));if(found)return row[found]}return undefined}
function rowsFrom(source:unknown):any[]{const out:any[]=[];const walk=(v:any)=>{if(Array.isArray(v))return v.forEach(walk);if(v&&typeof v==="object"){const keys=Object.keys(v).map(norm);if(keys.some(k=>k==="CODE"||k==="SUBJECTCODE"||k==="COURSECODE")&&keys.some(k=>k==="DATE"||k==="START"||k==="STARTTIME"))out.push(v);Object.values(v).forEach(walk)}};walk(source);return out}
function toIso(dateValue:any,timeValue:any){const date=String(dateValue||"").trim(),time=String(timeValue||"00:00").trim();if(!date)return null;const d=new Date(date.includes("T")?date:date+"T"+time+":00+05:30");return Number.isNaN(d.getTime())?null:d.toISOString()}
function buildEvents(data:unknown,selected:string[],sections:Record<string,string>){const rows=rowsFrom(data),events:SyncEvent[]=[];for(const row of rows){const code=norm(value(row,"code","subject code","course code"));if(!code||!selected.some(s=>norm(s)===code||norm(s).includes(code)||code.includes(norm(s))))continue;const section=String(value(row,"section")||"").trim().toUpperCase(),wanted=Object.values(sections).map(x=>x.toUpperCase());if(section&&wanted.length&&!wanted.includes(section))continue;const start=toIso(value(row,"date","class date","event date"),value(row,"start","start time","from")),end=toIso(value(row,"date","class date","event date"),value(row,"end","end time","to"));if(!start||!end)continue;const summary=String(value(row,"subject","subject name","course")||code),teacher=String(value(row,"teacher","faculty","professor")||""),type=String(value(row,"type","event type")||"Class"),sourceKey=[code,section,start,end,type].join("|");events.push({sourceKey,summary,description:[code,section?"Section "+section:"",teacher,type].filter(Boolean).join(" · "),start,end})}return events}
async function upsertProfile(profile:any,events:SyncEvent[]){const auth=new google.auth.OAuth2(process.env.GOOGLE_CLIENT_ID,process.env.GOOGLE_CLIENT_SECRET);auth.setCredentials(JSON.parse(decrypt(profile.token)));const calendar=google.calendar({version:"v3",auth}),previous=new Map(profile.events.map((e:SyncEvent)=>[e.sourceKey,e])),next:SyncEvent[]=[];for(const event of events){const old=previous.get(event.sourceKey),body={summary:event.summary,description:event.description,start:{dateTime:event.start},end:{dateTime:event.end},extendedProperties:{private:{studentCalendarSourceKey:event.sourceKey}}};let eventId=old?.eventId;if(eventId)await calendar.events.update({calendarId:"primary",eventId,requestBody:body});else{const r=await calendar.events.insert({calendarId:"primary",requestBody:body});eventId=r.data.id||undefined}next.push({...event,eventId})}for(const old of profile.events as SyncEvent[]){if(old.eventId&&!next.some(e=>e.sourceKey===old.sourceKey)){try{await calendar.events.delete({calendarId:"primary",eventId:old.eventId})}catch{}}}profile.events=next}
export async function GET(request:NextRequest){const secret=process.env.CRON_SECRET;if(secret&&request.headers.get("authorization")!=="Bearer "+secret)return NextResponse.json({ok:false},{status:401});try{const response=await fetch(SOURCE,{cache:"no-store",redirect:"follow"}),text=await response.text();let data:any;try{data=JSON.parse(text)}catch{data=null}const hash=crypto.createHash("sha256").update(text).digest("hex"),ids=await listProfileIds();let synced=0,skipped=0,failed=0;for(const id of ids){const profile=await getProfile(id);if(!profile||!profile.enabled)continue;try{if((profile as any).sourceHash===hash){profile.lastSyncAt=new Date().toISOString();await saveProfile(profile);skipped++;continue}const events=data?buildEvents(data,profile.selected,profile.sections):[];if(events.length){await upsertProfile(profile,events);(profile as any).sourceHash=hash;profile.lastError=undefined;synced++}else{profile.lastError="Official timetable response did not contain structured event rows, so existing calendar events were left unchanged.";skipped++}profile.lastSyncAt=new Date().toISOString();await saveProfile(profile)}catch(error){profile.lastError=error instanceof Error?error.message:"Sync failed";profile.lastSyncAt=new Date().toISOString();await saveProfile(profile);failed++}}return NextResponse.json({ok:true,synced,skipped,failed})}catch(error){return NextResponse.json({ok:false,error:error instanceof Error?error.message:"Cron sync failed"},{status:500})}}